=== erickvargas10/SOA_XML_DTD/Deber XML-DTD/src/java/Ejercicio2/recetas.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT recetas (receta)+>
<!ELEMENT receta (nombre, tipo,ingredientes, calorias, pasos, dificultad, tiempo, elaboracion)>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT tipo EMPTY>
<!ATTLIST tipo definicion (entrante | primero | segundo | postre) #REQUIRED>

<!ELEMENT ingredientes (ingrediente+)>
<!ELEMENT ingrediente EMPTY>
<!ATTLIST ingrediente nombre ID #REQUIRED>
<!ATTLIST ingrediente cantidad CDATA #REQUIRED>

<!ELEMENT calorias (#PCDATA)>

<!ELEMENT pasos (paso+)>
<!ELEMENT paso EMPTY>
<!ATTLIST paso orden ID #REQUIRED>


<!ELEMENT dificultad (#PCDATA)>


<!ELEMENT tiempo (#PCDATA)>


<!ELEMENT elaboracion (#PCDATA)>

=== erickvargas10/SOA_XML_DTD/Deber XML-DTD/src/java/Ejercicio2/recetas.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE recetas SYSTEM 'recetas.dtd'>

<recetas>
    <receta>
        <nombre>Pastel de chocolate</nombre>
        <tipo definicion="postre"/>
        <ingredientes>
            <ingrediente nombre="Harina" cantidad="3kg" />
            <ingrediente nombre="Azucar" cantidad="1kg" />
        </ingredientes>
        <calorias>220</calorias>
        <pasos>
            <paso orden= "mezclar "/>
            <paso orden= "hornear "/>
            <paso orden= "disfrutar "/>
        </pasos>
        <dificultad>Media</dificultad>
        <tiempo>2 horas</tiempo>
        <elaboracion>satisfactoria</elaboracion>

    </receta>
    
</recetas>
