=== erickvargas10/SOA_XML_DTD/XML-DTD/src/java/DTDaXML/Agenda.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT Agenda (contacto)*>
<!ELEMENT contacto (nombre,apellido+,telefono,email?,direccion)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT direccion (calle,numero,cp)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT cp (#PCDATA)>

<!ATTLIST telefono pais CDATA #REQUIRED>

=== erickvargas10/SOA_XML_DTD/XML-DTD/src/java/DTDaXML/Agenda.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Agenda SYSTEM 'Agenda.dtd'>

<Agenda>
    <contacto>
        <nombre>Erick</nombre>
        <apellido>Vargas</apellido>
        <telefono pais="Ecuador">0995361540</telefono>
        <email>erick.vargas01@epn.edu.ec</email>
        <direccion>
            <calle>Cayambe</calle>
            <numero>237</numero>
            <cp>145236</cp>
        </direccion>
    </contacto>

    
</Agenda>
